In [1]:
using Unicode

In [1]:
length("julia")

5

In [3]:
sizeof(""), sizeof("a"), sizeof("π"), sizeof("龙")

(0, 1, 2, 3)

In [4]:
"Hello, " * "World!"

"Hello, World!"

In [5]:
"Testing "^3

"Testing Testing Testing "

In [6]:
string(5), string(5, base=16, pad=4)

("5", "0005")

In [7]:
string(12345), string(12345, base=16, pad=5)

("12345", "03039")

In [8]:
string("a", "bc", "def", 1, true)

"abcdef1true"

In [9]:
repeat("ha", 3)

"hahaha"

In [11]:
repr(1), repr(zeros(3)), repr(1/3)

("1", "[0.0, 0.0, 0.0]", "0.3333333333333333")

In [12]:
repr(big(1/3))

"0.333333333333333314829616256247390992939472198486328125"

In [1]:
SubString("abc", 1, 2)

"ab"

In [3]:
SubString("abc", 1:2)

"ab"

In [5]:
SubString("abc", 2) # = 2:end

"bc"

In [6]:
ascii("abcd0123")

"abcd0123"

In [7]:
ascii("π")

LoadError: ArgumentError: invalid ASCII at index 1 in "π"

In [9]:
print(match(r"a+.*b+.*?d$"ism, "Goodbye,\nOh, angry\nBad world\n"))
# i: case insensitive; 
# s: . matches \n; 
# m: ^/$ match line ends, not whole str

RegexMatch("angry\nBad world")

In [10]:
SubstitutionString("Hello \\g<name>, it's \\1")

s"Hello \\g<name>, it's \\1"

In [11]:
subst = s"Hello \g<name>, it's\1"

s"Hello \\g<name>, it's\\1"

In [12]:
typeof(subst)

SubstitutionString{String}

In [14]:
msg = "#Hello# from Julia"
print(replace(
    msg, r"#(.+)# from (?<from>\w+)" => s"FROM: \g<from>\nMESSAGE: \1"))

FROM: Julia
MESSAGE: Hello

In [15]:
println(raw"\ $x")

\ $x


In [16]:
println(raw"\"")

"


In [17]:
println(raw"\\\"")

\"


In [18]:
println(raw"\\x \\\"")

\\x \"


In [1]:
isvalid(Char(0xd799)), print(Char(0xd799))

힙

(true, nothing)

In [2]:
isvalid(Char(0xd800))

false

In [4]:
s = String(UInt8[0xfe, 0x80, 0x80, 0x80, 0x80, 0x80])

"\xfe\x80\x80\x80\x80\x80"

In [6]:
isvalid(SubString(s, 1, 2))

false

In [7]:
isvalid(Char, 0xd800), isvalid(Char(0xd799))

(false, true)

In [8]:
isvalid(String, SubString("this is valid", 1, 5))

true

In [9]:
str = "αβγdef"
isvalid(str, 1)

true

In [10]:
str[1]

'α': Unicode U+03B1 (category Ll: Letter, lowercase)

In [12]:
isvalid(str, 2)

false

In [13]:
str[2]

LoadError: StringIndexError("αβγdef", 2)

In [14]:
rx = r"a(.)a"
m = match(rx, "cabac")

RegexMatch("aba", 1="b")

In [15]:
m.captures

1-element Array{Union{Nothing, SubString{String}},1}:
 "b"

In [16]:
m.match

"aba"

In [18]:
match(rx, "cabac", 3) === nothing

true

In [21]:
rx = r"a.a"
m = eachmatch(rx, "a1a2a3a")

Base.RegexMatchIterator(r"a.a", "a1a2a3a", false)

In [22]:
collect(m)

2-element Array{RegexMatch,1}:
 RegexMatch("a1a")
 RegexMatch("a3a")

In [23]:
isless("a", "b"), "a" < "b"

(true, true)

In [25]:
"abc" == "abc", "abc" == "ABC"

(true, false)

In [1]:
cmp("abc", "abc")

0

In [3]:
cmp("ab", "ac"), cmp("ab", "aba")

(-1, -1)

In [4]:
cmp("ba", "ab")

1

In [6]:
cmp("B", "a"), cmp("B", "A")

(-1, 1)

In [9]:
for month in ["February", "March", "April", "May"]
    print(".")
    println(lpad(month, 10))
end

.  February
.     March
.     April
.       May


In [10]:
for month in ["February", "March", "April", "May"]
    print(rpad(month, 10))
    println(".")
end

February  .
March     .
April     .
May       .


In [11]:
findfirst("o", "Hello, World!"), findfirst("z", "Hello, World!")

(5:5, nothing)

In [12]:
findfirst("ju", "Julia and jujubees")

11:12

In [13]:
findnext("o", "Hello, World!", 6)

9:9

In [14]:
findnext('o', "Hello, World!", 6)

9

In [3]:
findprev('o', "Hello, World", 8)

5

In [5]:
occursin("lia", "Juliana")

true

In [6]:
occursin(r"a.a", "aba")

true

In [7]:
reverse("etessawats")

"stawassete"

In [8]:
reverse("ax̂e")

"êxa"

In [14]:
join(reverse(collect(graphemes("ax̂e"))))

"ex̂a"

In [16]:
s = (
  "How much wood would a woodchuck chuck if a woodchuck could chuck wood?"
)
replace(replace(s, "wood" => "sand"), "chuck" => "box")

"How much sand would a sandbox box if a sandbox could box sand?"

In [17]:
replace(s, "wood" => "sand", count=1)

"How much sand would a woodchuck chuck if a woodchuck could chuck wood?"

In [20]:
split(s)

13-element Array{SubString{String},1}:
 "How"
 "much"
 "wood"
 "would"
 "a"
 "woodchuck"
 "chuck"
 "if"
 "a"
 "woodchuck"
 "could"
 "chuck"
 "wood?"

In [21]:
split(s, "wood")

5-element Array{SubString{String},1}:
 "How much "
 " would a "
 "chuck chuck if a "
 "chuck could chuck "
 "?"

In [22]:
a = "M*A*S*H"
rsplit(a, "*") # reverse

4-element Array{SubString{String},1}:
 "M"
 "A"
 "S"
 "H"

In [23]:
rsplit(a, "*", limit=2)

2-element Array{SubString{String},1}:
 "M*A*S"
 "H"

In [24]:
strip("    this   ")

"this"

In [25]:
strip("{3, 4}\n", ['{', '}', '\n'])

"3, 4"

In [3]:
lstrip("               stripper")

"stripper"

In [4]:
startswith("this line", "this")

true

In [5]:
startswith("that line", r"th(is|at|e)")

true

In [6]:
first("abcdefg")

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [7]:
first("abcdefg", 3)

"abc"

In [8]:
last("abcdefg", 2)

"fg"

In [9]:
uppercase("stop screaming")

"STOP SCREAMING"

In [10]:
lowercase("SORRY")

"sorry"

In [2]:
titlecase("the JULIA programming language")

"The Julia Programming Language"

In [4]:
titlecase("ISS: international space station", strict=false)

"ISS: International Space Station"

In [6]:
titlecase("a-a b-b"), titlecase("a-a b-b", wordsep=c -> c == ' ')

("A-A B-B", "A-a B-b")

In [7]:
join([1, 2, 3, 4, 5])

"12345"

In [8]:
join([1, 2, 3, 4, 5], "... ")

"1... 2... 3... 4... 5"

In [10]:
join(["alligators", "bears", "camels", "dingos"], ", ", " and ")

"alligators, bears, camels and dingos"

In [11]:
a = "March"
chop(a)

"Marc"

In [12]:
chop(a, head=1, tail=2)

"ar"

In [13]:
chop(a, head=5), chop(a, head=5, tail=5)

("", "")

In [14]:
chop(a, head=6)

""

In [15]:
chomp("Hello\n")

"Hello"

In [16]:
chomp("Hello\n\n")

"Hello\n"

In [2]:
textwidth('a')

1

In [3]:
textwidth('φ')

1

In [4]:
textwidth('字')

2

In [5]:
textwidth("March"), textwidth("三月")

(5, 4)

In [6]:
isascii("abc"), isascii("абв")

(true, false)

In [8]:
isdigit('9'), isdigit('b'), isdigit('३')

(true, false, false)

In [9]:
isletter('9'), isletter('b'), isletter('३')

(false, true, false)

In [10]:
isnumeric('9'), isnumeric('b'), isnumeric('३')

(true, false, true)

In [12]:
islowercase('A'), islowercase('a'), islowercase('Β'), islowercase('β'),
islowercase('あ'), islowercase('ア')

(false, true, false, true, false, false)

In [2]:
isprint('A'), isprint('\x01'), isprint('\n')

(true, false, false)

In [3]:
ispunct('a'), ispunct('/'), ispunct(';')

(false, true, true)

In [5]:
for char in [' ', '\t', '\n', '\x20', 'x']
    print("$(isspace(char)) ")
end

true true true true false 

In [6]:
isuppercase('Y'), isuppercase('Φ'), isuppercase('д')

(true, true, false)

In [9]:
isxdigit('f'), isxdigit('7'), isxdigit('x')

(true, true, false)

In [10]:
escape_string("aaa\nbb"), escape_string("\xfe\xff")

("aaa\\nbb", "\\xfe\\xff")

In [11]:
escape_string(string('\u2135', '\0'))

"ℵ\\0"

In [12]:
escape_string(string('\u2135', '\0', '0'))

"ℵ\\x000"