In [1]:
A = Array{Float64, 2}(undef, 2, 3)

2×3 Array{Float64,2}:
 2.18237e-314  2.18237e-314  2.18237e-314
 2.18237e-314  2.18237e-314  2.29888e-314

In [2]:
B = Array{Float64}(undef, 2)

2-element Array{Float64,1}:
 2.2378116083e-314
 2.444128497e-314

In [3]:
Array{Union{Nothing, Int}}(nothing, 2, 3)

2×3 Array{Union{Nothing, Int64},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [4]:
Array{Union{Nothing, String}}(nothing, 2)

2-element Array{Union{Nothing, String},1}:
 nothing
 nothing

In [5]:
Array{Union{Missing, String}}(missing, 2)

2-element Array{Union{Missing, String},1}:
 missing
 missing

In [6]:
Array{Union{Missing, Int}}(missing, 2, 3)

2×3 Array{Union{Missing, Int64},2}:
 missing  missing  missing
 missing  missing  missing

In [7]:
Array{Float64, 1}(UndefInitializer(), 3)

3-element Array{Float64,1}:
 2.2366077166e-314
 2.2803473245e-314
 2.182382834e-314

In [8]:
Array{Float64, 1}(undef, 3)

3-element Array{Float64,1}:
 2.2965547883e-314
 2.296554804e-314
 2.29655482e-314

In [9]:
Vector{Float64}(undef, 3) # a necesssarily 1D Array

3-element Array{Float64,1}:
 2.2965591835e-314
 2.2042036267e-314
 2.203118026e-314

In [1]:
Vector{Union{Nothing, String}}(nothing, 2)

2-element Array{Union{Nothing, String},1}:
 nothing
 nothing

In [3]:
Vector{Union{Missing, String}}(missing, 2)

2-element Array{Union{Missing, String},1}:
 missing
 missing

In [4]:
Matrix{Union{Nothing, String}}(nothing, 2, 3)

2×3 Array{Union{Nothing, String},2}:
 nothing  nothing  nothing
 nothing  nothing  nothing

In [5]:
Matrix{Union{Missing, String}}(missing, 3, 2)

3×2 Array{Union{Missing, String},2}:
 missing  missing
 missing  missing
 missing  missing

In [8]:
a = Int8[0, 1, 2, 3]
getindex(a, 2), getindex(a, 4)

(1, 3)

In [10]:
a[2], a[4]

(1, 3)

In [1]:
zeros(1)

1-element Array{Float64,1}:
 0.0

In [2]:
zeros(Int8, 2, 3)

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [3]:
ones(1, 2)

1×2 Array{Float64,2}:
 1.0  1.0

In [4]:
ones(ComplexF64, 2, 3)

2×3 Array{Complex{Float64},2}:
 1.0+0.0im  1.0+0.0im  1.0+0.0im
 1.0+0.0im  1.0+0.0im  1.0+0.0im

In [6]:
ba = BitArray(undef, 2, 2) # boolean only

2×2 BitArray{2}:
 0  0
 0  0

In [7]:
ba[1, 1] = 1

1

In [8]:
ba

2×2 BitArray{2}:
 1  0
 0  0

In [9]:
ba[2, 2] = 3

LoadError: InexactError: Bool(3)

In [10]:
BitArray(x + y == 3 for x = 1:2, y = 1:3)

2×3 BitArray{2}:
 0  1  0
 1  0  0

In [11]:
trues(2, 3)

2×3 BitArray{2}:
 1  1  1
 1  1  1

In [12]:
typeof(trues(2, 3))

BitArray{2}

In [13]:
fill(5, (2, 3))

2×3 Array{Int64,2}:
 5  5  5
 5  5  5