In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789

In [2]:
print(raw"a\tb")

a\tb

In [3]:
print("a\tb")

a	b

In [4]:
version = v"1.7.82"
version < v"1.6.6"

false

In [5]:
version.major, version.minor, version.patch

(0x00000001, 0x00000007, 0x00000052)

In [6]:
b"a2∑"

5-element Base.CodeUnits{UInt8, String}:
 0x61
 0x32
 0xe2
 0x88
 0x91

In [7]:
'∑'

'∑': Unicode U+2211 (category Sm: Symbol, math)

In [8]:
"a2\u03a3"

"a2Σ"

In [9]:
s = "abc"
replace(s, "b" => "xx", "c" => "ii")

"axxii"

In [10]:
replace(s, "b" => "xx", "x" => "ii")

"axxc"

In [11]:
occursin("def", "abcdefghi")

true

In [12]:
findfirst('c', "abcabc")

3

In [13]:
findlast('c', "abcabc")

6

In [14]:
findfirst("cab", "abcabc")

3:5

In [15]:
q = "To be or not to be, that is the question"
i = 0
locs = []
while i != nothing
    i = findnext('e', q, i + 1)
    if i != nothing
        push!(locs, i)
    end
end

locs

4-element Vector{Any}:
  5
 18
 31
 35

In [16]:
s = "abc<ABC>def"
replace(s, r"<.*>" => "")  # r is for regexes not raw like python

"abcdef"

In [17]:
replace(s, r"(.*)<(.*)>(.*)" => s"\1\3, \2")

"abcdef, ABC"

In [18]:
function namelength(name)
    println("Hello, $name. Your name is just $(length(name)) letters long.")
end

namelength (generic function with 1 method)

In [19]:
namelength("Fearthainn")

Hello, Fearthainn. Your name is just 10 letters long.


In [20]:
bd = Dict("one" => 1, "two" => 2)

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

In [21]:
bd["one"]

1

In [22]:
bd["one"] = 9
bd

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 9

In [23]:
Dict([("one", 1), ("two", 2)])

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

In [24]:
s1 = Set(1:5)

Set{Int64} with 5 elements:
  5
  4
  2
  3
  1

In [25]:
s2 = Set(4:8)
intersect(s1, s2)

Set{Int64} with 2 elements:
  5
  4

In [26]:
union(s1, s2)

Set{Int64} with 8 elements:
  5
  4
  6
  7
  2
  8
  3
  1

In [27]:
issubset(4:7, s2)

true

In [28]:
setdiff(s1, s2)

Set{Int64} with 3 elements:
  2
  3
  1

In [29]:
push!(s1, 999)
setdiff!(s1, 1:3)

Set{Int64} with 3 elements:
  5
  4
  999

In [30]:
struct Website
    url
    title
end

In [31]:
google = Website("https://www.google.com", "google")

Website("https://www.google.com", "google")

In [32]:
google.title

"google"

In [33]:
google.title = "Google"

LoadError: setfield!: immutable struct of type Website cannot be changed

In [34]:
mutable struct MutableWebsite
    url
    title
end

In [35]:
google = MutableWebsite("https://www.google.com", "google")
google.title = "Google"

"Google"

In [36]:
nt = (a=1, b=2, c=3)
nt.c

3

In [37]:
nt.a = 17

LoadError: setfield!: immutable struct of type NamedTuple cannot be changed

In [38]:
repeat(['a' 'b' '|'], 4)

4×3 Matrix{Char}:
 'a'  'b'  '|'
 'a'  'b'  '|'
 'a'  'b'  '|'
 'a'  'b'  '|'

In [39]:
repeat(['a' 'b' '|'], 4, 3)

4×9 Matrix{Char}:
 'a'  'b'  '|'  'a'  'b'  '|'  'a'  'b'  '|'
 'a'  'b'  '|'  'a'  'b'  '|'  'a'  'b'  '|'
 'a'  'b'  '|'  'a'  'b'  '|'  'a'  'b'  '|'
 'a'  'b'  '|'  'a'  'b'  '|'  'a'  'b'  '|'

In [40]:
xy = fill(['x', 'y'], 3)

3-element Vector{Vector{Char}}:
 ['x', 'y']
 ['x', 'y']
 ['x', 'y']

In [41]:
xy = fill(['x', 'y'], 3, 4)

3×4 Matrix{Vector{Char}}:
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']

In [42]:
xy[1, 4][1] = 'o'
xy

3×4 Matrix{Vector{Char}}:
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'y']
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'y']
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'y']

In [43]:
xy[1, 4] = ['o', 'z']
xy

3×4 Matrix{Vector{Char}}:
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'z']
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'y']
 ['o', 'y']  ['o', 'y']  ['o', 'y']  ['o', 'y']

In [44]:
xy  = [['x', 'y'] for i in 1:3, j in 1:4]

3×4 Matrix{Vector{Char}}:
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']

In [45]:
xy[1, 4][1] = 'o'
xy

3×4 Matrix{Vector{Char}}:
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['o', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']
 ['x', 'y']  ['x', 'y']  ['x', 'y']  ['x', 'y']

In [46]:
zeros(2, 3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [47]:
ones(3, 2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [48]:
a = collect(1:6)
a2 = reshape(a, (3, 2))

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [49]:
a[5] = 0
a2

3×2 Matrix{Int64}:
 1  4
 2  0
 3  6

In [52]:
m = [[1 2] [3 4]]

1×4 Matrix{Int64}:
 1  2  3  4

In [53]:
[[1 2]; [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

In [51]:
[[1 2];; [3 4]]

1×4 Matrix{Int64}:
 1  2  3  4

In [54]:
[[1 2];;; [3 4]]

1×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  2

[:, :, 2] =
 3  4