In [1]:
a = [1; 2; 3]
b = [1, 2, 3]
a == b

true

In [2]:
c = [1 2 3]
a == c

false

In [3]:
a

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
c

1×3 Array{Int64,2}:
 1  2  3

In [5]:
a = []
b = Int64[]

0-element Array{Int64,1}

In [6]:
a = Array{Int64, 1}()

0-element Array{Int64,1}

In [7]:
c = Vector{Int64}()

0-element Array{Int64,1}

In [8]:
a = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [9]:
a = zeros(Int64, 3)

3-element Array{Int64,1}:
 0
 0
 0

In [10]:
a = ones(Int64, 2)

2-element Array{Int64,1}:
 1
 1

In [11]:
a = Array{Int64, 1}(undef, 3)

3-element Array{Int64,1}:
 4628248528
 4628250096
 4439451600

In [12]:
a = fill(7.7, 3)

3-element Array{Float64,1}:
 7.7
 7.7
 7.7

In [13]:
a = rand(3)

3-element Array{Float64,1}:
 0.36979934496741573
 0.9249671245170339
 0.18793252999074905

In [14]:
a = 5:10

5:10

In [16]:
a = collect(5:0.5:7)

5-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0

In [17]:
collect(a[end:-1:1])

5-element Array{Float64,1}:
 7.0
 6.5
 6.0
 5.5
 5.0

In [18]:
y = [2015; 2025:2030; 2100]

8-element Array{Int64,1}:
 2015
 2025
 2026
 2027
 2028
 2029
 2030
 2100

In [20]:
y = vcat(2015, 2025:2028, 2100)

6-element Array{Int64,1}:
 2015
 2025
 2026
 2027
 2028
 2100

In [21]:
push!(a, 8)

6-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0
 8.0

In [22]:
pop!(a)

8.0

In [23]:
a

5-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0

In [25]:
popfirst!(a)

5.0

In [26]:
a

4-element Array{Float64,1}:
 5.5
 6.0
 6.5
 7.0

In [27]:
deleteat!(a, 3)

3-element Array{Float64,1}:
 5.5
 6.0
 7.0

In [28]:
pushfirst!(a, 5)

4-element Array{Float64,1}:
 5.0
 5.5
 6.0
 7.0