In [24]:
using Random

In [1]:
a = [1; 2; 3]
b = [1, 2, 3]
a == b

true

In [2]:
c = [1 2 3]
a == c

false

In [3]:
a

3-element Array{Int64,1}:
 1
 2
 3

In [4]:
c

1×3 Array{Int64,2}:
 1  2  3

In [5]:
a = []
b = Int64[]

0-element Array{Int64,1}

In [6]:
a = Array{Int64, 1}()

0-element Array{Int64,1}

In [7]:
c = Vector{Int64}()

0-element Array{Int64,1}

In [8]:
a = zeros(4)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [9]:
a = zeros(Int64, 3)

3-element Array{Int64,1}:
 0
 0
 0

In [10]:
a = ones(Int64, 2)

2-element Array{Int64,1}:
 1
 1

In [11]:
a = Array{Int64, 1}(undef, 3)

3-element Array{Int64,1}:
 4628248528
 4628250096
 4439451600

In [12]:
a = fill(7.7, 3)

3-element Array{Float64,1}:
 7.7
 7.7
 7.7

In [13]:
a = rand(3)

3-element Array{Float64,1}:
 0.36979934496741573
 0.9249671245170339
 0.18793252999074905

In [14]:
a = 5:10

5:10

In [16]:
a = collect(5:0.5:7)

5-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0

In [17]:
collect(a[end:-1:1])

5-element Array{Float64,1}:
 7.0
 6.5
 6.0
 5.5
 5.0

In [18]:
y = [2015; 2025:2030; 2100]

8-element Array{Int64,1}:
 2015
 2025
 2026
 2027
 2028
 2029
 2030
 2100

In [20]:
y = vcat(2015, 2025:2028, 2100)

6-element Array{Int64,1}:
 2015
 2025
 2026
 2027
 2028
 2100

In [21]:
push!(a, 8)

6-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0
 8.0

In [22]:
pop!(a)

8.0

In [23]:
a

5-element Array{Float64,1}:
 5.0
 5.5
 6.0
 6.5
 7.0

In [25]:
popfirst!(a)

5.0

In [26]:
a

4-element Array{Float64,1}:
 5.5
 6.0
 6.5
 7.0

In [27]:
deleteat!(a, 3)

3-element Array{Float64,1}:
 5.5
 6.0
 7.0

In [28]:
pushfirst!(a, 5)

4-element Array{Float64,1}:
 5.0
 5.5
 6.0
 7.0

In [1]:
sort!(rand(5))

5-element Array{Float64,1}:
 0.263131192362007
 0.3790470795886187
 0.4487543761995112
 0.8679261596606689
 0.9694815251855804

In [2]:
a = [1, 2, 2, 3, 3, 3, 4, 4, 4, 4]
u = unique(a)
u

4-element Array{Int64,1}:
 1
 2
 3
 4

In [3]:
a

10-element Array{Int64,1}:
 1
 2
 2
 3
 3
 3
 4
 4
 4
 4

In [4]:
unique!(a)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [5]:
reverse(u)

4-element Array{Int64,1}:
 4
 3
 2
 1

In [6]:
in(3, u)

true

In [7]:
length(u)

4

In [12]:
maximum(u), minimum(u)

(4, 1)

In [13]:
max(1, 3, 5, 7, 9, 1), min(1, 3, 5, 7, 9, 1)

(9, 1)

In [14]:
sum(u)

10

In [15]:
cumsum(u)

4-element Array{Int64,1}:
  1
  3
  6
 10

In [16]:
empty!(u)

0-element Array{Int64,1}

In [21]:
isempty(u)

true

In [19]:
a = [1 2 3 4]

1×4 Array{Int64,2}:
 1  2  3  4

In [20]:
vec(a)

4-element Array{Int64,1}:
 1
 2
 3
 4

In [25]:
shuffle!(a)

1×4 Array{Int64,2}:
 4  2  3  1

In [26]:
findall(x -> x < 3, a)

2-element Array{CartesianIndex{2},1}:
 CartesianIndex(1, 2)
 CartesianIndex(1, 4)

In [30]:
enumerate(a)

Base.Iterators.Enumerate{Array{Int64,2}}([4 2 3 1])

### Multidim and Nested Arrays

In [31]:
a = [[1, 2, 3] [4, 5, 6]]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [34]:
a = [1 4; 2 5; 3 6]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [35]:
a = Array{Int64}(undef, 0, 0, 0)

0×0×0 Array{Int64,3}

In [38]:
a = zeros(4, 3, 2)

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [40]:
ones(Int64, 4, 3, 2)

4×3×2 Array{Int64,3}:
[:, :, 1] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

[:, :, 2] =
 1  1  1
 1  1  1
 1  1  1
 1  1  1

In [41]:
a = Array{Int64, 3}(undef, 4, 3, 2)

4×3×2 Array{Int64,3}:
[:, :, 1] =
          3           1  4442218753
          1  4442218497           9
 4442218496           7           3
          5           2  4442219009

[:, :, 2] =
         12           4  4442219521
          4  4442219265          42
 4442219265          17          14
         14           5  4442219777

In [43]:
fill(2.2, 2, 2, 2)

2×2×2 Array{Float64,3}:
[:, :, 1] =
 2.2  2.2
 2.2  2.2

[:, :, 2] =
 2.2  2.2
 2.2  2.2

In [44]:
rand(2, 2, 2)

2×2×2 Array{Float64,3}:
[:, :, 1] =
 0.41217   0.623661
 0.521303  0.683685

[:, :, 2] =
 0.315372  0.12501
 0.155507  0.825345

In [45]:
[x + 2y + 3z for x in 1:2, y in 2:3, z in 3:4]

2×2×2 Array{Int64,3}:
[:, :, 1] =
 14  16
 15  17

[:, :, 2] =
 17  19
 18  20

In [46]:
a = [1, 2, 3]
push!(a, [1 2])

MethodError: MethodError: Cannot `convert` an object of type Array{Int64,2} to an object of type Int64
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T<:Number at number.jl:6
  convert(::Type{T}, !Matched::Number) where T<:Number at number.jl:7
  convert(::Type{T}, !Matched::Ptr) where T<:Integer at pointer.jl:23
  ...

In [48]:
a = [[1, 2, 3] [4, 5, 6]]
mask = [[true, true, false] [false, true, false]]
a[mask]

3-element Array{Int64,1}:
 1
 2
 5

In [49]:
size(a)

(3, 2)

In [50]:
a

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [51]:
ndims(a)

2

In [52]:
reshape(a, 2, 3)

2×3 Array{Int64,2}:
 1  3  5
 2  4  6

In [56]:
reshape(a, 1, 3, 2)

1×3×2 Array{Int64,3}:
[:, :, 1] =
 1  2  3

[:, :, 2] =
 4  5  6

In [60]:
a = rand(2, 1, 3)

2×1×3 Array{Float64,3}:
[:, :, 1] =
 0.8017890421273024
 0.3342063842162275

[:, :, 2] =
 0.8299416165027882
 0.07285292761109141

[:, :, 3] =
 0.14876365829228733
 0.7157342824334871

In [62]:
b = dropdims(a, dims=(2))

2×3 Array{Float64,2}:
 0.801789  0.829942   0.148764
 0.334206  0.0728529  0.715734

In [63]:
b'

3×2 LinearAlgebra.Adjoint{Float64,Array{Float64,2}}:
 0.801789  0.334206
 0.829942  0.0728529
 0.148764  0.715734