In [1]:
n = 0
while n < 10
    n += 1
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [3]:
peeps = ["Aleasdair", "Brianna", "Catriona", "Domhnail", "Eilidh"]
i = 1
while i < length(peeps)
    println("$(peeps[i]), meet $(peeps[i + 1])")
    i += 1
end

Aleasdair, meet Brianna
Brianna, meet Catriona
Catriona, meet Domhnail
Domhnail, meet Eilidh


In [4]:
for n in 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [5]:
for n = 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [6]:
for name in peeps
    println("$name is ainm dom")
end

Aleasdair is ainm dom
Brianna is ainm dom
Catriona is ainm dom
Domhnail is ainm dom
Eilidh is ainm dom


In [7]:
m, n = 9, 9
kuku = zeros(m, n)

for i in 1:m
    for j in 1:n
        kuku[i, j] = i * j
    end
end
kuku

9×9 Matrix{Float64}:
 1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
 2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0
 3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0
 4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0
 5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0
 6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0
 7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0
 8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0
 9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0

In [8]:
kuku = zeros(m, n)
for i in 1:m, j in 1:n
    kuku[i, j] = i * j
end
kuku

9×9 Matrix{Float64}:
 1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
 2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0
 3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0
 4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0
 5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0
 6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0
 7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0
 8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0
 9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0

In [9]:
kuku = [i * j for i in 1:m, j in 1:n]
kuku

9×9 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

In [10]:
for n in 1:5
    A = [i * j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 1

2×2 Matrix{Int64}:
 1  2
 2  4

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Matrix{Int64}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [11]:
x = rand()
y = rand()

if x > y
    println("$x > $y")
elseif x < y
    println("$x < $y")
else
    println("$x = $y")
end

0.9596909345944273 > 0.40916881618652945


In [12]:
x = rand()
y = rand()

if x > y 
    x
else
    y
end

0.9415371146106625

In [13]:
x > y ? x : y

0.9415371146106625

In [14]:
(x > y) && println("$x > $y")

false

In [15]:
(x > y) || println("$x < $y")

0.3361887009566179 < 0.9415371146106625


In [16]:
function greet(person="Stranger")
    println("Howdy, $person")
end

greet (generic function with 2 methods)

In [17]:
greet()

Howdy, Stranger


In [18]:
greet("Roy")

Howdy, Roy


In [19]:
function sq(x)
    x^2
end

sq (generic function with 1 method)

In [20]:
sq(9)

81

In [21]:
greet(name="Stranger") = println("Howdy, $(name)!")
sq(x) = x^2

sq (generic function with 1 method)

In [22]:
greet("Doc")

Howdy, Doc!


In [23]:
sq(7)

49

In [24]:
salute = name -> println("Hey there, $(name)!")
sqr = x -> x^2

#11 (generic function with 1 method)

In [25]:
salute("Calamity Jane")

Hey there, Calamity Jane!


In [26]:
sqr(5)

25

In [27]:
salute(7)

Hey there, 7!


In [28]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.289126  0.940723  0.0233174
 0.735701  0.253197  0.611101
 0.594246  0.241054  0.491299

In [29]:
sqr(A) # AA (mat mult)

3×3 Matrix{Float64}:
 0.789541  0.515796  0.593074
 0.762132  0.903508  0.472117
 0.641108  0.738484  0.40254

In [30]:
sqr.(A)  # element-wise

3×3 Matrix{Float64}:
 0.0835939  0.884959   0.000543703
 0.541257   0.0641086  0.373444
 0.353128   0.058107   0.241375

In [35]:
v = rand(5)

5-element Vector{Float64}:
 0.9967163873152362
 0.12609860930419203
 0.5470377379152697
 0.12703549313782558
 0.8957800661558262

In [36]:
#sqr(v) # undef
sqr.(v)

5-element Vector{Float64}:
 0.9934435567427359
 0.015900859268451265
 0.29925028670345527
 0.01613801651677053
 0.8024219269221363

In [37]:
sort(v)

5-element Vector{Float64}:
 0.12609860930419203
 0.12703549313782558
 0.5470377379152697
 0.8957800661558262
 0.9967163873152362

In [38]:
v

5-element Vector{Float64}:
 0.9967163873152362
 0.12609860930419203
 0.5470377379152697
 0.12703549313782558
 0.8957800661558262

In [39]:
sort!(v)

5-element Vector{Float64}:
 0.12609860930419203
 0.12703549313782558
 0.5470377379152697
 0.8957800661558262
 0.9967163873152362

In [40]:
v

5-element Vector{Float64}:
 0.12609860930419203
 0.12703549313782558
 0.5470377379152697
 0.8957800661558262
 0.9967163873152362