In [1]:
n = 0
while n < 10
    n += 1
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [5]:
peeps = ["Aleasdair", "Brianna", "Chatriona", "Domhnail", "Eilidh"]
i = 1
while i < length(peeps) - 1
    println("$(peeps[i]), meet $(peeps[i + 1])")
    i += 1
end

Aleasdair, meet Brianna
Brianna, meet Chatriona
Chatriona, meet Domhnail


In [6]:
for n in 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [9]:
for n = 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [8]:
for name in peeps
    println("$name is ainm dom")
end

Aleasdair is ainm dom
Brianna is ainm dom
Chatriona is ainm dom
Domhnail is ainm dom
Eilidh is ainm dom


In [12]:
m, n = 9, 9
kuku = zeros(m, n)

for i in 1:m
    for j in 1:n
        kuku[i, j] = i * j
    end
end
kuku

9×9 Array{Float64,2}:
 1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
 2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0
 3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0
 4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0
 5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0
 6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0
 7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0
 8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0
 9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0

In [13]:
kuku = zeros(m, n)
for i in 1:m, j in 1:n
    kuku[i, j] = i * j
end
kuku

9×9 Array{Float64,2}:
 1.0   2.0   3.0   4.0   5.0   6.0   7.0   8.0   9.0
 2.0   4.0   6.0   8.0  10.0  12.0  14.0  16.0  18.0
 3.0   6.0   9.0  12.0  15.0  18.0  21.0  24.0  27.0
 4.0   8.0  12.0  16.0  20.0  24.0  28.0  32.0  36.0
 5.0  10.0  15.0  20.0  25.0  30.0  35.0  40.0  45.0
 6.0  12.0  18.0  24.0  30.0  36.0  42.0  48.0  54.0
 7.0  14.0  21.0  28.0  35.0  42.0  49.0  56.0  63.0
 8.0  16.0  24.0  32.0  40.0  48.0  56.0  64.0  72.0
 9.0  18.0  27.0  36.0  45.0  54.0  63.0  72.0  81.0

In [14]:
kuku = [i * j for i in 1:m, j in 1:n]
kuku

9×9 Array{Int64,2}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

In [15]:
for n in 1:5
    A = [i * j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Array{Int64,2}:
 1

2×2 Array{Int64,2}:
 1  2
 2  4

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

4×4 Array{Int64,2}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Array{Int64,2}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [18]:
x = rand()
y = rand()

if x > y
    println("$x > $y")
elseif x < y
    println("$x < $y")
else
    println("$x = $y")
end

0.6407577985872295 < 0.8406128551720538


In [19]:
x = rand()
y = rand()

if x > y 
    x
else
    y
end

0.7555197057700738

In [20]:
x > y ? x : y

0.7555197057700738

In [21]:
(x > y) && println("$x > $y")

0.7555197057700738 > 0.22458573365537782


In [22]:
(x > y) || println("$x < $y")

true

In [23]:
function greet(person="Stranger")
    println("Howdy, $person")
end

greet (generic function with 2 methods)

In [24]:
greet()

Howdy, Stranger


In [25]:
greet("Roy")

Howdy, Roy


In [26]:
function sq(x)
    x^2
end

sq (generic function with 1 method)

In [27]:
sq(9)

81

In [30]:
greet(name="Stranger") = println("Howdy, $(name)!")
sq(x) = x^2

sq (generic function with 1 method)

In [31]:
greet("Doc")

Howdy, Doc!


In [32]:
sq(7)

49

In [34]:
salute = name -> println("Hey there, $(name)!")
sqr = x -> x^2

#9 (generic function with 1 method)

In [35]:
salute("Calamity Jane")

Hey there, Calamity Jane!


In [36]:
sqr(5)

25

In [37]:
salute(7)

Hey there, 7!


In [42]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.991685  0.925658  0.509857
 0.935127  0.487462  0.599217
 0.171761  0.204523  0.274385

In [43]:
sqr(A) # AA (mat mult)

3×3 Array{Float64,2}:
 1.93662   1.47346   1.20018
 1.48611   1.22578   0.933293
 0.408716  0.314807  0.285414

In [46]:
sqr.(A)

3×3 Array{Float64,2}:
 0.983438   0.856842   0.259954
 0.874462   0.237619   0.359062
 0.0295018  0.0418295  0.075287

In [44]:
v = rand(3)

3-element Array{Float64,1}:
 0.6629233232702638
 0.4064902769600587
 0.6659351401621729

In [47]:
#sqr(v) # undef
sqr.(v)

3-element Array{Float64,1}:
 0.4394673325356907
 0.1652343452630652
 0.4434696109028129

In [48]:
sort(v)

3-element Array{Float64,1}:
 0.4064902769600587
 0.6629233232702638
 0.6659351401621729

In [49]:
v

3-element Array{Float64,1}:
 0.6629233232702638
 0.4064902769600587
 0.6659351401621729

In [50]:
sort!(v)

3-element Array{Float64,1}:
 0.4064902769600587
 0.6629233232702638
 0.6659351401621729

In [51]:
v

3-element Array{Float64,1}:
 0.4064902769600587
 0.6629233232702638
 0.6659351401621729