In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#234567890
n = 0
while n < 10
    n += 1
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [2]:
peeps = ["Aleasdair", "Brianna", "Catriona", "Domhnail", "Eilidh"]
i = 1
while i < length(peeps)
    println("$(peeps[i]), meet $(peeps[i + 1])")
    i += 1
end

Aleasdair, meet Brianna
Brianna, meet Catriona
Catriona, meet Domhnail
Domhnail, meet Eilidh


In [3]:
for n in 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [4]:
for n = 1:10
    print("$n ")
end

1 2 3 4 5 6 7 8 9 10 

In [5]:
for name in peeps
    println("$name is ainm dom")
end

Aleasdair is ainm dom
Brianna is ainm dom
Catriona is ainm dom
Domhnail is ainm dom
Eilidh is ainm dom


In [9]:
m, n = 9, 9
kuku = zeros(Int, m, n)

for i in 1:m
    for j in 1:n
        kuku[i, j] = i * j
    end
end
kuku

9×9 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

In [10]:
kuku = zeros(Int, m, n)
for i in 1:m, j in 1:n
    kuku[i, j] = i * j
end
kuku

9×9 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

In [11]:
kuku = [i * j for i in 1:m, j in 1:n]
kuku

9×9 Matrix{Int64}:
 1   2   3   4   5   6   7   8   9
 2   4   6   8  10  12  14  16  18
 3   6   9  12  15  18  21  24  27
 4   8  12  16  20  24  28  32  36
 5  10  15  20  25  30  35  40  45
 6  12  18  24  30  36  42  48  54
 7  14  21  28  35  42  49  56  63
 8  16  24  32  40  48  56  64  72
 9  18  27  36  45  54  63  72  81

In [12]:
for n in 1:5
    A = [i * j for i in 1:n, j in 1:n]
    display(A)
end

1×1 Matrix{Int64}:
 1

2×2 Matrix{Int64}:
 1  2
 2  4

3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

5×5 Matrix{Int64}:
 1   2   3   4   5
 2   4   6   8  10
 3   6   9  12  15
 4   8  12  16  20
 5  10  15  20  25

In [13]:
x = rand()
y = rand()

if x > y
    println("$x > $y")
elseif x < y
    println("$x < $y")
else
    println("$x = $y")
end

0.0844721984673229 < 0.8037300964674138


In [14]:
x = rand()
y = rand()

if x > y 
    x
else
    y
end

0.8696377685971043

In [15]:
x > y ? x : y

0.8696377685971043

In [16]:
(x > y) && println("$x > $y")

false

In [17]:
(x > y) || println("$x < $y")

0.1283995705532145 < 0.8696377685971043


In [18]:
function greet(person="Stranger")
    println("Howdy, $person")
end

greet (generic function with 2 methods)

In [19]:
greet()

Howdy, Stranger


In [20]:
greet("Roy")

Howdy, Roy


In [21]:
function sq(x)
    x^2
end

sq (generic function with 1 method)

In [22]:
sq(9)

81

In [23]:
greet(name="Stranger") = println("Howdy, $(name)!")
sq(x) = x^2

sq (generic function with 1 method)

In [24]:
greet("Doc")

Howdy, Doc!


In [25]:
sq(7)

49

In [26]:
salute = name -> println("Hey there, $(name)!")
sqr = x -> x^2

#11 (generic function with 1 method)

In [27]:
salute("Calamity Jane")

Hey there, Calamity Jane!


In [28]:
sqr(5)

25

In [29]:
salute(7)

Hey there, 7!


In [30]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.842876  0.149898  0.865705
 0.35783   0.151306  0.206466
 0.472792  0.316449  0.528524

In [31]:
sqr(A) # AA (mat mult)

3×3 Matrix{Float64}:
 1.17338   0.422977  1.21818
 0.453363  0.141867  0.450136
 0.761621  0.286002  0.753971

In [32]:
sqr.(A)  # element-wise

3×3 Matrix{Float64}:
 0.71044   0.0224693  0.749445
 0.128042  0.0228934  0.0426281
 0.223532  0.10014    0.279337

In [33]:
v = rand(5)

5-element Vector{Float64}:
 0.31579769395913393
 0.8694212475627859
 0.27615683409626957
 0.5199787675603293
 0.9378755133963069

In [34]:
#sqr(v) # undef
sqr.(v)

5-element Vector{Float64}:
 0.09972818350990681
 0.7558933057136311
 0.07626259701807456
 0.27037791871355904
 0.8796104786283863

In [35]:
sort(v)

5-element Vector{Float64}:
 0.27615683409626957
 0.31579769395913393
 0.5199787675603293
 0.8694212475627859
 0.9378755133963069

In [36]:
v

5-element Vector{Float64}:
 0.31579769395913393
 0.8694212475627859
 0.27615683409626957
 0.5199787675603293
 0.9378755133963069

In [37]:
sort!(v)

5-element Vector{Float64}:
 0.27615683409626957
 0.31579769395913393
 0.5199787675603293
 0.8694212475627859
 0.9378755133963069

In [38]:
v

5-element Vector{Float64}:
 0.27615683409626957
 0.31579769395913393
 0.5199787675603293
 0.8694212475627859
 0.9378755133963069