In [62]:
import Base: + # to overload

using LinearAlgebra

In [2]:
#methods(+)

In [3]:
@which 3 + 3

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} in Base at int.jl:86

In [4]:
@which 3. + 3.

+(x::Float64, y::Float64) in Base at float.jl:401

In [5]:
@which 3 + 3.

+(x::Number, y::Number) in Base at promotion.jl:311

In [7]:
"hello, " + "World!"

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538

In [8]:
@which "hello, " + "World!"

LoadError: no unique matching method found for the specified argument types

In [9]:
+(x::String, y::String) = x * y

+ (generic function with 185 methods)

In [10]:
"hello, " + "World!"

"hello, World!"

In [11]:
foo(x, y) = println("duck-typed foo")
foo(x::Int, y::Float64) = println("int-float foo")
foo(x::Float64, y::Float64) = println("floatie foo")
foo(x::UInt, y::UInt) = println("foo on U")

foo (generic function with 4 methods)

In [12]:
foo(1, 1)

duck-typed foo


In [13]:
foo(2., 3.)

floatie foo


In [14]:
foo(UInt(1), UInt(2))

foo on U


In [15]:
foo(true, false)

duck-typed foo


In [1]:
A = rand(1:4, 3, 3)

3×3 Array{Int64,2}:
 3  1  2
 3  2  4
 2  2  2

In [2]:
B = A # same obj!
C = copy(A)
[B C]

3×6 Array{Int64,2}:
 3  1  2  3  1  2
 3  2  4  3  2  4
 2  2  2  2  2  2

In [3]:
A[1] = 9
[B C]

3×6 Array{Int64,2}:
 9  1  2  3  1  2
 3  2  4  3  2  4
 2  2  2  2  2  2

In [4]:
x = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [5]:
b = A*x

3-element Array{Float64,1}:
 12.0
  9.0
  6.0

In [6]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 9  3  2
 1  2  2
 2  4  2

In [7]:
Asym = A + A'

3×3 Array{Int64,2}:
 18  4  4
  4  4  6
  4  6  4

In [8]:
Apd = A'A

3×3 Array{Int64,2}:
 94  19  34
 19   9  14
 34  14  24

In [10]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 1.0

In [14]:
Atall = A[:, 1:2] # overdetermined

3×2 Array{Int64,2}:
 9  1
 3  2
 2  2

In [15]:
Atall \ b 

2-element Array{Float64,1}:
 1.0824742268041239
 2.3814432989690717

In [16]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.522099  0.235046  0.0100019
 0.394768  0.278898  0.0112673
 0.491317  0.465802  0.86556

In [18]:
[A[:, 1] A[:, 1]] \ b # solution with smallest norm

2-element Array{Float64,1}:
 9.529409674816078
 9.529409674816078

In [19]:
Ashort = A[1:2, :]

2×3 Array{Float64,2}:
 0.522099  0.235046  0.0100019
 0.394768  0.278898  0.0112673

In [20]:
Ashort \ b[1:2]

3-element Array{Float64,1}:
 23.31071689676133
 -0.7268672161994407
  0.035687129311295585

### Matrix Factorization

In [21]:
A = rand(3, 3)

3×3 Array{Float64,2}:
 0.923444  0.410891   0.435965
 0.282115  0.0189326  0.258701
 0.238168  0.384864   0.546782

In [24]:
l, u, p = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.257913   1.0       0.0
 0.305503  -0.382215  1.0
U factor:
3×3 Array{Float64,2}:
 0.923444  0.410891  0.435965
 0.0       0.27889   0.434341
 0.0       0.0       0.291524

In [27]:
# Pivoting on so cannot assume A = LU:
norm(l*u - A)

0.6615556850378572

In [28]:
norm(l*u - A[p, :])

2.7755575615628914e-17

In [29]:
p

3-element Array{Int64,1}:
 1
 3
 2

In [36]:
# or turn off pivoting
l, u, p = lu(A, Val(false))
norm(l*u - A)

6.206335383118183e-17

In [47]:
Alu = lu(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.257913   1.0       0.0
 0.305503  -0.382215  1.0
U factor:
3×3 Array{Float64,2}:
 0.923444  0.410891  0.435965
 0.0       0.27889   0.434341
 0.0       0.0       0.291524

In [40]:
x = ones(3)
b = A * x

3-element Array{Float64,1}:
 1.7703000096657588
 0.5597482847258108
 1.1698143375925574

In [50]:
#Alu[:U] \ (Alu[:L] \ (Alu[:P]b))

In [51]:
Alu \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000004
 0.9999999999999998

In [42]:
det(A)

-0.07507891535370073

In [52]:
det(Alu)

-0.07507891535370073

In [53]:
Aqr = qr(A[:, 1:2])

LinearAlgebra.QRCompactWY{Float64,Array{Float64,2}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64,Array{Float64,2}}:
 -0.928536  -0.114534  -0.353132
 -0.28367   -0.394721   0.873914
 -0.239481   0.911634   0.334023
R factor:
2×2 Array{Float64,2}:
 -0.994516  -0.479066
  0.0        0.296321

In [54]:
Asym = A + A'

3×3 Array{Float64,2}:
 1.84689   0.693006   0.674133
 0.693006  0.0378651  0.643565
 0.674133  0.643565   1.09356

In [64]:
Asym_eig = eigen(Asym)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
values:
3-element Array{Float64,1}:
 -0.33361248965073687
  0.7312083958142721
  2.5807220709975343
vectors:
3×3 Array{Float64,2}:
  0.19333   -0.581271  -0.79041
 -0.925399   0.159626  -0.343738
  0.325975   0.797899  -0.507047

In [65]:
inv(Asym_eig) * Asym

3×3 Array{Float64,2}:
 1.0          -8.88178e-16   2.9976e-15
 1.11022e-15   1.0          -4.66294e-15
 1.4988e-15    1.11022e-16   1.0

In [66]:
Asvd = svd(A[:, 1:2])

SVD{Float64,Float64,Array{Float64,2}}
U factor:
3×2 Array{Float64,2}:
 -0.907469  -0.22759
 -0.233099  -0.426542
 -0.34952    0.875365
singular values:
2-element Array{Float64,1}:
 1.1118070302195786
 0.26506048278488914
Vt factor:
2×2 Array{Float64,2}:
 -0.887746  -0.460333
 -0.460333   0.887746

In [67]:
Asvd \ b

2-element Array{Float64,1}:
 1.0493517305265172
 2.1690631073558224

### Structured Matrices

In [68]:
A

3×3 Array{Float64,2}:
 0.923444  0.410891   0.435965
 0.282115  0.0189326  0.258701
 0.238168  0.384864   0.546782

In [69]:
diag(A)

3-element Array{Float64,1}:
 0.9234440644294368
 0.01893256540188748
 0.5467823587492082

In [70]:
Diagonal(diag(A))

3×3 Diagonal{Float64,Array{Float64,1}}:
 0.923444   ⋅          ⋅ 
  ⋅        0.0189326   ⋅ 
  ⋅         ⋅         0.546782

In [72]:
Diagonal(A)

3×3 Diagonal{Float64,Array{Float64,1}}:
 0.923444   ⋅          ⋅ 
  ⋅        0.0189326   ⋅ 
  ⋅         ⋅         0.546782

In [73]:
LowerTriangular(A)

3×3 LowerTriangular{Float64,Array{Float64,2}}:
 0.923444   ⋅          ⋅ 
 0.282115  0.0189326   ⋅ 
 0.238168  0.384864   0.546782

In [75]:
Asym

3×3 Array{Float64,2}:
 1.84689   0.693006   0.674133
 0.693006  0.0378651  0.643565
 0.674133  0.643565   1.09356

In [74]:
Symmetric(Asym)

3×3 Symmetric{Float64,Array{Float64,2}}:
 1.84689   0.693006   0.674133
 0.693006  0.0378651  0.643565
 0.674133  0.643565   1.09356

In [76]:
SymTridiagonal(diag(Asym), diag(Asym, 1))

3×3 SymTridiagonal{Float64,Array{Float64,1}}:
 1.84689   0.693006    ⋅ 
 0.693006  0.0378651  0.643565
  ⋅        0.643565   1.09356

In [78]:
n = 1000
A = rand(n, n)
Asym1 = A + A'
Asym2 = copy(Asym1)
Asym2[1, 2] += 5eps() # add noise

issymmetric(Asym1), issymmetric(Asym2)

(true, false)

In [80]:
@time eigvals(Asym1);

  0.121217 seconds (11 allocations: 7.989 MiB)


In [81]:
@time eigvals(Asym2);

  0.768444 seconds (13 allocations: 7.920 MiB)


In [84]:
@time eigvals(Symmetric(Asym2));

  0.113768 seconds (12 allocations: 7.989 MiB)


In [85]:
rand(1:10, 3, 3) * rand(1:10, 3, 3)

3×3 Array{Int64,2}:
 114  74  134
  39  49   34
  99  87  105

In [86]:
Ar = convert(Matrix{Rational{BigInt}}, rand(1:10, 3, 3)) / 10

3×3 Array{Rational{BigInt},2}:
 9//10  2//5   1//10
 9//10  1//2   1//2
 1//2   1//10  3//10

In [87]:
x = ones(Int, 3)
b = Ar * x

3-element Array{Rational{BigInt},1}:
  7//5
 19//10
  9//10

In [89]:
Ar \ b

3-element Array{Rational{BigInt},1}:
 1//1
 1//1
 1//1

In [88]:
lu(Ar)

LU{Rational{BigInt},Array{Rational{BigInt},2}}
L factor:
3×3 Array{Rational{BigInt},2}:
 1//1   0//1   0//1
 5//9   1//1   0//1
 1//1  -9//11  1//1
U factor:
3×3 Array{Rational{BigInt},2}:
 9//10    2//5    1//10
 0//1   -11//90  11//45
 0//1     0//1    3//5

In [90]:
lmb1, lmb2, lmb3 = 1//1, 1//2, 1//4
v1, v2, v3 = [1, 0, 0], [1, 1, 0], [1, 1, 1]
V, LMB = [v1 v2 v3], Diagonal([lmb1, lmb2, lmb3])
A = V * LMB / V

3×3 Array{Rational{Int64},2}:
 1//1  -1//2  -1//4
 0//1   1//2  -1//4
 0//1   0//1   1//4