In [1]:
import Base: + # to overload

using LinearAlgebra

In [2]:
#methods(+)

In [3]:
@which 3 + 3

+(x::T, y::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}
     @ Base int.jl:87

In [4]:
@which 3. + 3.

+(x::T, y::T) where T<:Union{Float16, Float32, Float64}
     @ Base float.jl:495

In [5]:
@which 3 + 3.

+(x::Number, y::Number)
     @ Base promotion.jl:433

In [6]:
"hello, " + "World!"

LoadError: MethodError: no method matching +(::String, ::String)
The function `+` exists, but no method is defined for this combination of argument types.
String concatenation is performed with * (See also: https://docs.julialang.org/en/v1/manual/strings/#man-concatenation).

Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...)
   @ Base operators.jl:642
  +(::BigInt, ::BigInt)
   @ Base gmp.jl:502
  +(::BigInt, ::BigInt, ::BigInt)
   @ Base gmp.jl:542
  ...


In [7]:
@which "hello, " * "World!"

*(s1::Union{AbstractChar, AbstractString}, ss::Union{AbstractChar, AbstractString}...)
     @ Base strings/basic.jl:262

In [8]:
+(x::String, y::String) = x * y

+ (generic function with 190 methods)

In [9]:
"hello, " + "World!"

"hello, World!"

In [10]:
foo(x, y) = println("duck-typed foo")
foo(x::Int, y::Float64) = println("int-float foo")
foo(x::Float64, y::Float64) = println("floatie foo")
foo(x::UInt, y::UInt) = println("foo on U")

foo (generic function with 4 methods)

In [11]:
foo(1, 1)

duck-typed foo


In [12]:
foo(2., 3.)

floatie foo


In [13]:
foo(UInt(1), UInt(2))

foo on U


In [17]:
foo(true, false)

duck-typed foo


## Structs

In [14]:
struct MyObj
    field1
    field2
end

In [15]:
hello = MyObj("Hello", "World")

MyObj("Hello", "World")

In [16]:
hello.field2

"World"

In [17]:
hello.field2 = "Dave"

LoadError: setfield!: immutable struct of type MyObj cannot be changed

In [18]:
mutable struct Person
    name::String
    age::Int32
end

In [19]:
me = Person("Damian", 48)

Person("Damian", 48)

In [20]:
me.age += 1
me.age

49

In [21]:
mutable struct Person
    name::String
    age::Int32
    isActive

    function Person(name, age)
        new(name, age, true)
    end
end

In [22]:
you = Person("Bob", 73)

Person("Bob", 73, true)

In [23]:
function grow(person::Person)
    person.age += 1
end

grow (generic function with 1 method)

In [25]:
grow(you)
me.age

49

In [18]:
A = rand(1:4, 3, 3)

3×3 Matrix{Int64}:
 2  4  2
 1  3  2
 3  4  1

In [19]:
B = A # same obj!
C = copy(A)
[B C]

3×6 Matrix{Int64}:
 2  4  2  2  4  2
 1  3  2  1  3  2
 3  4  1  3  4  1

In [20]:
A[1] = 9
[B C]

3×6 Matrix{Int64}:
 9  4  2  2  4  2
 1  3  2  1  3  2
 3  4  1  3  4  1

In [21]:
x = ones(3)

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [22]:
b = A*x

3-element Vector{Float64}:
 15.0
  6.0
  8.0

In [23]:
A'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 9  1  3
 4  3  4
 2  2  1

In [24]:
Asym = A + A'

3×3 Matrix{Int64}:
 18  5  5
  5  6  6
  5  6  2

In [25]:
Apd = A'A

3×3 Matrix{Int64}:
 91  51  23
 51  41  18
 23  18   9

In [26]:
A \ b

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [27]:
Atall = A[:, 1:2] # overdetermined

3×2 Matrix{Int64}:
 9  4
 1  3
 3  4

In [28]:
Atall \ b 

2-element Vector{Float64}:
 1.0221238938053092
 1.4115044247787614

In [29]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.906129  0.0448564  0.909134
 0.550429  0.909286   0.842835
 0.610126  0.271935   0.0319723

In [30]:
[A[:, 1] A[:, 1]] \ b # solution with smallest norm

2-element Vector{Float64}:
 7.276475608839634
 7.276475608839633

In [31]:
Ashort = A[1:2, :]

2×3 Matrix{Float64}:
 0.906129  0.0448564  0.909134
 0.550429  0.909286   0.842835

In [32]:
Ashort \ b[1:2]

3-element Vector{Float64}:
  9.454639560484196
 -5.955815471325479
  7.369687381293801

### Matrix Factorization

In [33]:
A = rand(3, 3)

3×3 Matrix{Float64}:
 0.242381   0.757216  0.0750331
 0.0404849  0.21689   0.408286
 0.314477   0.365996  0.17471

In [34]:
l, u, p = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.770745  1.0       0.0
 0.128737  0.357321  1.0
U factor:
3×3 Matrix{Float64}:
 0.314477  0.365996   0.17471
 0.0       0.475126  -0.0596238
 0.0       0.0        0.407099

In [35]:
# Pivoting on so cannot assume A = LU:
norm(l*u - A)

0.8739676120798571

In [36]:
norm(l*u - A[p, :])

0.0

In [37]:
p

3-element Vector{Int64}:
 3
 1
 2

In [38]:
# or turn off pivoting
l, u, p = lu(A, Val(false))
norm(l*u - A)

2.2215299868541707e-16

In [39]:
Alu = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.770745  1.0       0.0
 0.128737  0.357321  1.0
U factor:
3×3 Matrix{Float64}:
 0.314477  0.365996   0.17471
 0.0       0.475126  -0.0596238
 0.0       0.0        0.407099

In [40]:
x = ones(3)
b = A * x

3-element Vector{Float64}:
 1.0746303286276686
 0.6656606400945858
 0.8551827411074234

In [41]:
#Alu[:U] \ (Alu[:L] \ (Alu[:P]b))

In [42]:
Alu \ b

3-element Vector{Float64}:
 0.9999999999999998
 1.0000000000000002
 0.9999999999999999

In [43]:
det(A)

0.060827160754878096

In [44]:
det(Alu)

0.060827160754878096

In [45]:
Aqr = qr(A[:, 1:2])

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
2×2 Matrix{Float64}:
 -0.399103  -0.770259
  0.0       -0.401336

In [46]:
Asym = A + A'

3×3 Matrix{Float64}:
 0.484763  0.797701  0.38951
 0.797701  0.43378   0.774282
 0.38951   0.774282  0.34942

In [47]:
Asym_eig = eigen(Asym)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
3-element Vector{Float64}:
 -0.5086973412128348
  0.027129450200689686
  1.7495308729139205
vectors:
3×3 Matrix{Float64}:
  0.415844  -0.712448   -0.565235
 -0.761022   0.0676763  -0.645187
  0.497915   0.698454   -0.514046

In [48]:
inv(Asym_eig) * Asym

3×3 Matrix{Float64}:
 1.0          -5.32907e-15  -3.55271e-15
 1.33227e-15   1.0           1.66533e-15
 1.24345e-14   1.95399e-14   1.0

In [49]:
Asvd = svd(A[:, 1:2])

SVD{Float64, Float64, Matrix{Float64}, Vector{Float64}}
U factor:
3×2 Matrix{Float64}:
 -0.841805  -0.424571
 -0.229113  -0.27808
 -0.488744   0.861632
singular values:
2-element Vector{Float64}:
 0.9405595775222009
 0.1702970622667492
Vt factor:
2×2 Matrix{Float64}:
 -0.390206  -0.920727
  0.920727  -0.390206

In [50]:
Asvd \ b

2-element Vector{Float64}:
 1.1282416586157196
 1.2252069603609665

### Structured Matrices

In [51]:
A

3×3 Matrix{Float64}:
 0.242381   0.757216  0.0750331
 0.0404849  0.21689   0.408286
 0.314477   0.365996  0.17471

In [52]:
diag(A)

3-element Vector{Float64}:
 0.2423814203720296
 0.21688998858376374
 0.17471008199509552

In [53]:
Diagonal(diag(A))

3×3 Diagonal{Float64, Vector{Float64}}:
 0.242381   ⋅        ⋅ 
  ⋅        0.21689   ⋅ 
  ⋅         ⋅       0.17471

In [54]:
Diagonal(A)

3×3 Diagonal{Float64, Vector{Float64}}:
 0.242381   ⋅        ⋅ 
  ⋅        0.21689   ⋅ 
  ⋅         ⋅       0.17471

In [55]:
LowerTriangular(A)

3×3 LowerTriangular{Float64, Matrix{Float64}}:
 0.242381    ⋅         ⋅ 
 0.0404849  0.21689    ⋅ 
 0.314477   0.365996  0.17471

In [56]:
Asym

3×3 Matrix{Float64}:
 0.484763  0.797701  0.38951
 0.797701  0.43378   0.774282
 0.38951   0.774282  0.34942

In [57]:
Symmetric(Asym)

3×3 Symmetric{Float64, Matrix{Float64}}:
 0.484763  0.797701  0.38951
 0.797701  0.43378   0.774282
 0.38951   0.774282  0.34942

In [58]:
SymTridiagonal(diag(Asym), diag(Asym, 1))

3×3 SymTridiagonal{Float64, Vector{Float64}}:
 0.484763  0.797701   ⋅ 
 0.797701  0.43378   0.774282
  ⋅        0.774282  0.34942

In [59]:
n = 1000
A = rand(n, n)
Asym1 = A + A'
Asym2 = copy(Asym1)
Asym2[1, 2] += 5eps() # add noise

issymmetric(Asym1), issymmetric(Asym2)

(true, false)

In [60]:
@time eigvals(Asym1);

  0.649282 seconds (2.73 M allocations: 144.392 MiB, 13.08% gc time, 82.62% compilation time)


In [61]:
@time eigvals(Asym2);

  0.276494 seconds (27 allocations: 7.985 MiB)


In [62]:
@time eigvals(Symmetric(Asym2));

  0.074237 seconds (15.31 k allocations: 8.802 MiB, 5.70% gc time, 20.53% compilation time)


In [63]:
rand(1:10, 3, 3) * rand(1:10, 3, 3)

3×3 Matrix{Int64}:
 198  167  107
 100   67   46
 118  102   53

In [64]:
Ar = convert(Matrix{Rational{BigInt}}, rand(1:10, 3, 3)) / 10

3×3 Matrix{Rational{BigInt}}:
 1//2  3//10  3//5
 1//5  4//5    1
 1//2  9//10  3//10

In [65]:
x = ones(Int, 3)
b = Ar * x

3-element Vector{Rational{BigInt}}:
  7//5
   2
 17//10

In [66]:
Ar \ b

3-element Vector{Rational{BigInt}}:
 1
 1
 1

In [67]:
lu(Ar)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
  1      0     0
 2//5    1     0
  1    15//17  1
U factor:
3×3 Matrix{Rational{BigInt}}:
 1//2   3//10    3//5
  0    17//25   19//25
  0      0     -33//34

In [68]:
lmb1, lmb2, lmb3 = 1//1, 1//2, 1//4
v1, v2, v3 = [1, 0, 0], [1, 1, 0], [1, 1, 1]
V, LMB = [v1 v2 v3], Diagonal([lmb1, lmb2, lmb3])
A = V * LMB / V

3×3 Matrix{Rational{Int64}}:
 1  -1//2  -1//4
 0   1//2  -1//4
 0    0     1//4