In [3]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789
import ImageMagick
using Images
using PlutoUI
using HypertextLiteral

### Ex 1

In [7]:
rv = [rand() for r in 1:10]
rv

10-element Vector{Float64}:
 0.05990177085990167
 0.7566049146329046
 0.514089583982933
 0.5845948752990444
 0.09623435394369129
 0.494053146302626
 0.51180715327512
 0.18294027910680177
 0.8472278451973612
 0.9982406420357278

In [11]:
function my_sum(v)
    s = 0
    for i in v
        s = s + i
    end
    s
end

my_sum (generic function with 1 method)

In [12]:
my_sum(rv)

5.045694564636112

In [13]:
sum(rv)

5.045694564636112

In [17]:
function mean(v)
    my_sum(v) / length(v)
end

mean (generic function with 1 method)

In [19]:
m = mean(rv)
m

0.5045694564636112

In [20]:
function deviation(v)
    m = mean(v)
    v .- m
end

deviation (generic function with 1 method)

In [21]:
deviation(rv)

10-element Vector{Float64}:
 -0.4446676856037095
  0.2520354581692934
  0.009520127519321853
  0.08002541883543324
 -0.4083351025199199
 -0.010516310160985198
  0.007237696811508876
 -0.3216291773568094
  0.34265838873375
  0.49367118557211664

In [22]:
test_v = [-1., -1.5, 8.5]
mean(test_v)

2.0

In [23]:
deviation(test_v)

3-element Vector{Float64}:
 -3.0
 -3.5
  6.5

In [24]:
mean(deviation(test_v))

0.0

In [30]:
function create_bar()
    v = zeros(100)
    v[40:60] .= 1
    v
end

create_bar (generic function with 1 method)

In [31]:
create_bar()

100-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

### Ex 2