In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789

In [2]:
Inf

Inf

In [3]:
[1; 2; 3; 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
[1;; 2;; 3;; 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [5]:
[[1, 2], [3, 4]]

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [6]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [7]:
[1 2
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
typeof(Inf)

Float64

In [9]:
reshape([1, 2, 3, 4], (2, 2))

2×2 Matrix{Int64}:
 1  3
 2  4

In [10]:
a = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [11]:
a + a

4-element Vector{Int64}:
 2
 4
 6
 8

In [12]:
a * reshape(a, (1, length(a)))

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [13]:
a / a

4×4 Matrix{Float64}:
 0.0333333  0.0666667  0.1  0.133333
 0.0666667  0.133333   0.2  0.266667
 0.1        0.2        0.3  0.4
 0.133333   0.266667   0.4  0.533333

In [14]:
Float32.([4.3, 5, 0])

3-element Vector{Float32}:
 4.3
 5.0
 0.0

In [15]:
f(x) = 7x^2 / (4 + 5x^3)

f (generic function with 1 method)

In [16]:
x = [2π / n for n = 1:3]

3-element Vector{Float64}:
 6.283185307179586
 3.141592653589793
 2.0943951023931953

In [17]:
y = f.(x)

3-element Vector{Float64}:
 0.22210061177582122
 0.43442513879920297
 0.6149053316945388

In [18]:
x = [2, 4, 5]
y = 3x.^3 + 6x.^5

3-element Vector{Int64}:
   216
  6336
 19125

In [19]:
y = sin.(x)

3-element Vector{Float64}:
  0.9092974268256817
 -0.7568024953079282
 -0.9589242746631385

In [20]:
ex = rand(5, 7)

5×7 Matrix{Float64}:
 0.676961  0.191717  0.853798  0.116479  0.38037   0.663818  0.739991
 0.279876  0.347833  0.241389  0.754012  0.341434  0.331299  0.800372
 0.657819  0.832282  0.666995  0.867599  0.247098  0.832418  0.911953
 0.584356  0.680215  0.152568  0.523252  0.511092  0.768831  0.853603
 0.782498  0.08527   0.580982  0.957666  0.64376   0.906409  0.43516

In [21]:
ex1 = rand(Int64, 5, 7)

5×7 Matrix{Int64}:
 -6107089559537917727  -7991378752977461805  …  -1891839855687759993
 -5329975558950809442   5285293350539713260      2521094294521065581
  1715622817755669473   3422423793887715937     -3942017023990552005
  2117239877335030104  -3805853097123379244       567717970441171818
 -7090312426876477259   -889996928036030566      2756794794875345630

In [22]:
length(ex)

35