In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789

In [2]:
Inf

Inf

In [3]:
[1; 2; 3; 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
[1;; 2;; 3;; 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [5]:
[[1, 2], [3, 4]]

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [6]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [7]:
[1 2
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
typeof(Inf)

Float64

In [9]:
reshape([1, 2, 3, 4], (2, 2))

2×2 Matrix{Int64}:
 1  3
 2  4

In [10]:
a = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [11]:
a + a

4-element Vector{Int64}:
 2
 4
 6
 8

In [12]:
a * reshape(a, (1, length(a)))

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [13]:
a / a

4×4 Matrix{Float64}:
 0.0333333  0.0666667  0.1  0.133333
 0.0666667  0.133333   0.2  0.266667
 0.1        0.2        0.3  0.4
 0.133333   0.266667   0.4  0.533333

In [14]:
Float32.([4.3, 5, 0])

3-element Vector{Float32}:
 4.3
 5.0
 0.0

In [15]:
f(x) = 7x^2 / (4 + 5x^3)

f (generic function with 1 method)

In [16]:
x = [2π / n for n = 1:3]

3-element Vector{Float64}:
 6.283185307179586
 3.141592653589793
 2.0943951023931953

In [17]:
y = f.(x)

3-element Vector{Float64}:
 0.22210061177582122
 0.43442513879920297
 0.6149053316945388

In [18]:
x = [2, 4, 5]
y = 3x.^3 + 6x.^5

3-element Vector{Int64}:
   216
  6336
 19125

In [19]:
y = sin.(x)

3-element Vector{Float64}:
  0.9092974268256817
 -0.7568024953079282
 -0.9589242746631385

In [20]:
ex = rand(5, 7)

5×7 Matrix{Float64}:
 0.973294   0.522628   0.0375018  0.437954  0.905691   0.637518  0.256942
 0.492483   0.547353   0.462311   0.473748  0.632264   0.453112  0.983886
 0.0930462  0.594877   0.190212   0.080669  0.121929   0.942751  0.278297
 0.181067   0.964983   0.931175   0.60804   0.0457078  0.740246  0.291115
 0.631865   0.0730197  0.21214    0.170849  0.0381376  0.590371  0.458647

In [21]:
ex1 = rand(Int64, 5, 7)

5×7 Matrix{Int64}:
  6962682040689853067   4617095061113035874  …   -837766811697024421
  3839419691737321639   7865905657490820686      2047769045435606947
 -6054372065486504542  -6942978352259953269     -1862098770733719657
  4182425912045089873  -4382858997032914653     -6299346599434724316
  8067387441547453471   5718287063293020960     -5927954979854863144

In [22]:
length(ex)

35

In [23]:
a = 4
b = a
n = copy(a)
a = 6
(a, b, n)

(6, 4, 4)

In [24]:
r = [3.4, 5]
s = r
r[1] = 3
t = copy(r)
r[2] = 7
(r, s, t)

([3.0, 7.0], [3.0, 7.0], [3.0, 5.0])

In [25]:
g = 7
typeof(g)

Int64

In [26]:
h = 45.6
typeof(h)

Float64

In [28]:
try
    log(-54)
catch e
    println("Can't be negative")
    println(e)
end

Can't be negative
DomainError(-54.0, "log was called with a negative real argument but will only return a complex result if called with a complex argument. Try log(Complex(x)).")


In [29]:
p = try
    log(-54)
catch e
    throw(e)
finally
    println("Always log me")
end

Always log me


LoadError: DomainError with -54.0:
log was called with a negative real argument but will only return a complex result if called with a complex argument. Try log(Complex(x)).

In [33]:
for x in range(1, 1, 3)
    println("Yo")
end

Yo
Yo
Yo
