In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789

In [2]:
Inf

Inf

In [3]:
[1; 2; 3; 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [4]:
[1;; 2;; 3;; 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [5]:
[[1, 2], [3, 4]]

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [6]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [7]:
[1 2
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [8]:
typeof(Inf)

Float64

In [9]:
reshape([1, 2, 3, 4], (2, 2))

2×2 Matrix{Int64}:
 1  3
 2  4

In [10]:
a = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [11]:
a + a

4-element Vector{Int64}:
 2
 4
 6
 8

In [12]:
a * reshape(a, (1, length(a)))

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [13]:
a / a

4×4 Matrix{Float64}:
 0.0333333  0.0666667  0.1  0.133333
 0.0666667  0.133333   0.2  0.266667
 0.1        0.2        0.3  0.4
 0.133333   0.266667   0.4  0.533333

In [14]:
Float32.([4.3, 5, 0])

3-element Vector{Float32}:
 4.3
 5.0
 0.0

In [15]:
f(x) = 7x^2 / (4 + 5x^3)

f (generic function with 1 method)

In [16]:
x = [2π / n for n = 1:3]

3-element Vector{Float64}:
 6.283185307179586
 3.141592653589793
 2.0943951023931953

In [17]:
y = f.(x)

3-element Vector{Float64}:
 0.22210061177582122
 0.43442513879920297
 0.6149053316945388

In [18]:
x = [2, 4, 5]
y = 3x.^3 + 6x.^5

3-element Vector{Int64}:
   216
  6336
 19125

In [19]:
y = sin.(x)

3-element Vector{Float64}:
  0.9092974268256817
 -0.7568024953079282
 -0.9589242746631385

In [20]:
ex = rand(5, 7)

5×7 Matrix{Float64}:
 0.942612  0.9588    0.0932227   0.927212  0.677037   0.408649  0.120803
 0.422801  0.387523  0.548039    0.236963  0.0913378  0.617095  0.0236744
 0.154118  0.634052  0.00017463  0.108042  0.461477   0.469413  0.303602
 0.296228  0.38012   0.929734    0.366911  0.143737   0.243297  0.114983
 0.575621  0.99425   0.0356867   0.309621  0.530096   0.641785  0.883563

In [21]:
ex1 = rand(Int64, 5, 7)

5×7 Matrix{Int64}:
 -3950795472945448684  -9146045038422526025  …   4726932805515540085
  3195108945015448762  -6631826455132421956     -6035182964044329869
  2709020839715309818   3158839281440625690     -7586231438680073498
 -9068069111770267671   2809795779569769483      6851004810388694929
 -4021184224172751456  -1752229394057283738     -1561838471518819512

In [22]:
length(ex)

35

In [23]:
a = 4
b = a
n = copy(a)
a = 6
(a, b, n)

(6, 4, 4)

In [25]:
r = [3.4, 5]
s = r
r[1] = 3
t = copy(r)
r[2] = 7
(r, s, t)

([3.0, 7.0], [3.0, 7.0], [3.0, 5.0])

In [26]:
g = 7
typeof(g)

Int64

In [27]:
h = 45.6
typeof(h)

Float64