In [1]:
#234567890#234567890#234567890#234567890#234567890#234567890#234567890#23456789

In [1]:
Inf

Inf

In [2]:
[1; 2; 3; 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [3]:
[1;; 2;; 3;; 4]

1×4 Matrix{Int64}:
 1  2  3  4

In [4]:
[[1, 2], [3, 4]]

2-element Vector{Vector{Int64}}:
 [1, 2]
 [3, 4]

In [5]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [6]:
[1 2
 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [7]:
typeof(Inf)

Float64

In [8]:
reshape([1, 2, 3, 4], (2, 2))

2×2 Matrix{Int64}:
 1  3
 2  4

In [9]:
a = [1, 2, 3, 4]

4-element Vector{Int64}:
 1
 2
 3
 4

In [10]:
a + a

4-element Vector{Int64}:
 2
 4
 6
 8

In [11]:
a * reshape(a, (1, length(a)))

4×4 Matrix{Int64}:
 1  2   3   4
 2  4   6   8
 3  6   9  12
 4  8  12  16

In [12]:
a / a

4×4 Matrix{Float64}:
 0.0333333  0.0666667  0.1  0.133333
 0.0666667  0.133333   0.2  0.266667
 0.1        0.2        0.3  0.4
 0.133333   0.266667   0.4  0.533333

In [15]:
Float32.([4.3, 5, 0])

3-element Vector{Float32}:
 4.3
 5.0
 0.0