In [19]:
using InteractiveUtils

- `import Module` imports the module and Module.fn(x) calls fn()
- `using Module` imports all exported Module functions, types, and macros

### Measuring Performance

In [2]:
function fib(n::Int64)
    sum([1:100000])
    nothing # code here...
end

fib (generic function with 1 method)

In [3]:
fib(1)

In [4]:
@time fib(40)

  0.000005 seconds (5 allocations: 256 bytes)


In [5]:
@time fib(40)

  0.000002 seconds (5 allocations: 256 bytes)


### Collections and Data Structures

In [1]:
function subtract(dict1, dict2)
    res = Dict()
    for key in keys(dict1)
        if !(key in keys(dict2))
            res[key] = nothing
        end
    end
    res
end

subtract (generic function with 1 method)

In [4]:
# Prev equivalent to
dict1 = Dict("a" => 1, "b" => 2, "c" => 3)
dict2 = Dict("a" => 1, "b" => 2, "d" => 4)
setdiff(dict1, dict2)

1-element Array{Pair{String,Int64},1}:
 "c" => 3

In [5]:
function hasduplicates(t)
    d = Dict()
    for x in t
        if x in d
            return true
        end
        d[x] = nothing
    end
    false
end

hasduplicates (generic function with 1 method)

In [6]:
# equivalent to:
function hasduplicates2(t)
    length(Set(t)) < length(t)
end

hasduplicates2 (generic function with 1 method)

In [7]:
function usesonly(word, available)
    for letter in word
        if !(letter in available)
            return false
        end
    end
    true
end

usesonly (generic function with 1 method)

In [8]:
function usesonly2(word, available)
    Set(word) ⊆ Set(available)
end

usesonly2 (generic function with 1 method)

### Mathematics

In [11]:
ℯ^(im*π) + 1

0.0 + 1.2246467991473532e-16im

In [12]:
x = 0:0.1:2π
cos.(x) == 0.5*(ℯ.^(im*x) + ℯ.^(-im*x))

true

### Strings

In [13]:
function usesonly3(word, available)
    r = Regex("[^$(available)]")
    !occursin(r, word)
end

usesonly3 (generic function with 1 method)

In [14]:
usesonly3("banana", "abn")

true

In [15]:
usesonly3("bananer", "abn")

false

In [18]:
m = match(r"[^abn]", "bananas")

RegexMatch("s")

In [19]:
m.match

"s"

In [20]:
m.offset

7

### Arrays

In [1]:
z = zeros(Float64, 2, 3)

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [2]:
typeof(z)

Array{Float64,2}

In [3]:
size(z)

(2, 3)

In [4]:
s = ones(String, 1, 3)

1×3 Array{String,2}:
 ""  ""  ""

In [7]:
s2 = ["", "", ""]
s == s2

false

In [8]:
typeof(s), typeof(s2)

(Array{String,2}, Array{String,1})

In [9]:
a = [1 2 3; 4 5 6]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [10]:
z[1, 2] = 1
z[2, 3] = 2
z

2×3 Array{Float64,2}:
 0.0  1.0  0.0
 0.0  0.0  2.0

In [11]:
u = z[:, 2:end]

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  2.0

In [12]:
ℯ.^(im * u)

2×2 Array{Complex{Float64},2}:
 0.540302+0.841471im        1.0+0.0im     
      1.0+0.0im       -0.416147+0.909297im

### Interfaces

In [13]:
struct Fibonacci{T <: Real} end

Fibonacci(d::DataType) = (
    d <: Real ? Fibonacci{d}() : error("Not a Real type!"))

Fibonacci

In [14]:
Base.iterate(::Fibonacci{T}) where {T <: Real} = (
    zero(T), (one(T), one(T)))

In [15]:
Base.iterate(::Fibonacci{T}, state::Tuple{T, T}) where {T <: Real} = (
    state[1], (state[2], state[1] + state[2]))

In [16]:
for f in Fibonacci(Int64)
    f > 100 && break
    print(f, " ")
end

0 1 1 2 3 5 8 13 21 34 55 89 

### Interactive Utilities

In [17]:
function sumofsquares(a::Float64, b::Float64)
    a^2 + b^2
end

sumofsquares (generic function with 1 method)

In [20]:
@code_lowered sumofsquares(3., 4)

0-element Array{Union{Nothing, CodeInfo},1}